config/routes.rb
Pharaoh::Application.routes.draw do

  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end

  authenticate :user, lambda { |user| user.is_admin? } do
    mount PgHero::Engine, at: 'system/admin/db/pg'
  end

  root to: 'static_pages#index'

  resources :styles, only: :index

  devise_for :users,
    controllers: {
      passwords: 'users/passwords',
      unlocks: 'users/unlocks',
      confirmations: 'users/confirmations'
    },
    skip: [:sessions, :registrations]

  devise_scope :user do
    # sessions
    get 'login', to: 'users/sessions#new', as: :new_user_session
    post 'login', to: 'users/sessions#create', as: :user_session
    delete 'logout', to: 'users/sessions#destroy', as: :destroy_user_session

    # registrations
    get 'register', to: 'users/registrations#new',
      as: :new_user_registration

    get 'account/cancel',
      to: 'users/registrations#cancel',
      as: :cancel_user_registration

    post 'account',
      to: 'users/registrations#create',
      as: :user_registration

    get 'account/edit',
      to: 'users/registrations#edit',
      as: :edit_user_registration

    patch 'account', to: 'users/registrations#update', as: ''
    put 'account', to: 'users/registrations#update', as: ''
    delete 'account', to: 'users/registrations#destroy', as: ''
  end

  concern :pagination do
    get 'page/:page', action: :index, on: :collection
  end

  scope 'system' do
    namespace :admin do
      root to: 'static_pages#index', as: :root #= admin_root

      resources :users, concerns: :pagination do
        collection do
          post 'enable/:id', action: :enable, as: :enable
        end
      end

      namespace :server do
        resources :stats, only: :index do
          get 'processes', on: :collection
        end
      end
    end
  end
end

app/controllers/admin/static_pages_controller.rb
class Admin::StaticPagesController < Admin::BaseController

  def index
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout 'guest/application'

  def index
  end
end

app/views/admin/static_pages/index.html.erb
<% content_for :title do %>Admin Control Panel<% end %>

<div class="container">
  <div class="text-center">
    <%= render 'layouts/admin/header' %>
  </div>

  <div class="well well-lg">
    <div class="row">
      <div class="col-md-4">
        <%= link_to(
          admin_users_path,
          class: 'admin-link'
        ) do %>
          <h1 class="text-center">
            <%= fa_icon 'group 5x' %>
          </h1>
        <% end %>

        <h2 class="text-center">User Management</h2>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <hr class="well-hr">
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <%= link_to(pg_hero_path, class: 'admin-link') do %>
          <h1 class="text-center">
            <%= fa_icon 'database 5x' %>
          </h1>
        <% end %>

        <h2 class="text-center">Database</h2>
      </div>

      <div class="col-md-4">
        <%= link_to(admin_server_stats_path, class: 'admin-link') do %>
          <h1 class="text-center">
            <%= fa_icon 'dashboard 5x' %>
          </h1>
        <% end %>

        <h2 class="text-center">Passenger</h2>
      </div>

      <div class="col-md-4">
        <%= link_to(processes_admin_server_stats_path, class: 'admin-link') do %>
          <h1 class="text-center">
            <%= fa_icon 'tasks 5x' %>
          </h1>
        <% end %>

        <h2 class="text-center">Processes</h2>
      </div>
    </div>
  </div>
</div>