config/routes.rb
Pharaoh::Application.routes.draw do

  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end

  authenticate :user, lambda { |user| user.is_admin? } do
    mount PgHero::Engine, at: 'system/admin/db/pg'
  end

  root to: 'static_pages#index'

  resources :styles, only: :index

  devise_for :users,
    controllers: {
      passwords: 'users/passwords',
      unlocks: 'users/unlocks',
      confirmations: 'users/confirmations'
    },
    skip: [:sessions, :registrations]

  devise_scope :user do
    # sessions
    get 'login', to: 'users/sessions#new', as: :new_user_session
    post 'login', to: 'users/sessions#create', as: :user_session
    delete 'logout', to: 'users/sessions#destroy', as: :destroy_user_session

    # registrations
    get 'register', to: 'users/registrations#new',
      as: :new_user_registration

    get 'account/cancel',
      to: 'users/registrations#cancel',
      as: :cancel_user_registration

    post 'account',
      to: 'users/registrations#create',
      as: :user_registration

    get 'account/edit',
      to: 'users/registrations#edit',
      as: :edit_user_registration

    patch 'account', to: 'users/registrations#update', as: ''
    put 'account', to: 'users/registrations#update', as: ''
    delete 'account', to: 'users/registrations#destroy', as: ''
  end

  concern :pagination do
    get 'page/:page', action: :index, on: :collection
  end

  scope 'system' do
    namespace :admin do
      root to: 'static_pages#index', as: :root #= admin_root

      resources :users, concerns: :pagination do
        collection do
          post 'enable/:id', action: :enable, as: :enable
        end
      end

      namespace :server do
        resources :stats, only: :index do
          get 'processes', on: :collection
        end
      end
    end
  end
end

app/views/layouts/_breadcrumbs.html.erb
<% if content_for?(:breadcrumbs) %>
  <%= yield(:breadcrumbs) %>
<% elsif breadcrumbs.present? %>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <%= render_breadcrumbs(builder: BootstrapBreadcrumbsBuilder) %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= alert_class_for(type) %> alert-dismissable fade in">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-wa-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        Pharaoh.io
    </div>

    <div class="collapse navbar-collapse navbar-wa-collapse">
      <ul class="nav navbar-nav navbar-left">
        <li>
          <a href="/">Dashboard</a>
        </li>
        <% if current_user.is_admin? %>
          <li>
            <%= link_to 'Admin', admin_root_path %>
          </li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <%= link_to 'Settings', edit_user_registration_path %>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to 'Logout', destroy_user_session_path, method: 'delete' %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=320, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes"/>

  <title><%= content_for?(:title) ? "#{yield(:title)} - Pharaoh" : "Pharaoh" %></title>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= yield(:stylesheets) %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= yield(:javascripts) %>

  <%= csrf_meta_tags %>

  <%= yield(:head) %>
</head>

<body class="<%= controller_class %> <%= action_name %>">

  <div id="wrap">
    <%= render 'layouts/nav' %>

    <div class="spacer"></div>

    <%= render 'layouts/messages' %>

    <%= yield %>
  </div>

    <%= render 'layouts/footer'%>

    <%= raw EXTERNAL_JS %>
    <%= yield(:inline_javascript) %>
</body>
</html>